# -*- coding: utf-8 -*-
"""
S Log notification content, per category. English, Gen Z tone (Zomato-style: playful, warm,
a bit cheeky, sometimes emotional). Short: <= 36 characters / 7 words before the emoji.

Each category has:
  keywords  - words in a log name that map it to this category (the app uses them too)
  names     - example log names people type
  emoji     - 2-3 single-code-point emoji, reused across the category
  lines     - hand-written complete messages (no emoji; one is added when building rows)
  questions - short question-style nudges
  actions   - lowercase imperative phrases, combined with openers / closers
  nouns     - words for the category, used in fun templates ("Water o'clock!")
"""

CATEGORIES = {
    # ------------------------------------------------------------------ body & health
    "hydration": dict(
        keywords=["water", "drink", "hydrat", "bottle", "h2o", "glass of", "litre", "liter", "2l", "3l",
                  "coconut", "electrolyte", "paani", "pani"],
        names=["Drink Water", "Water", "Hydrate", "2L Water", "Water Bottle", "Drink 8 Glasses", "Hydration",
               "Water Break", "3L Water", "Morning Water", "Glass of Water", "H2O", "Coconut Water",
               "Refill Bottle", "Warm Water", "Water Goal", "Electrolytes"],
        emoji=["💧", "🥤", "🚰"],
        lines=[
            "Your bottle feels ignored", "Sip sip hooray", "Hydrate or diedrate", "Water you waiting for?",
            "Your cells are thirsty, bestie", "One glass. Right now.", "Your skin called. It wants water",
            "Stay wavy, drink water", "Plants drink more than you", "Hydration is self-love",
            "Glass half empty? Fix it", "Your brain is 75% water", "Water first, coffee later",
            "Dry vibes are not the vibe", "Glow starts with a glass", "Small sips, big wins",
            "Your kidneys say thank you", "Main characters drink water", "Fill it, finish it",
            "Hydrated people simply slay", "Don't leave your bottle on read", "Your body is a plant. Water it",
            "Sip now, thank us later", "The hydration station is open", "Hydration era starts now",
            "No cap, water is free", "Be the hydrated icon you are", "Water check, bestie",
            "Chug a little, glow a lot", "It's giving well-watered", "Thirst is a red flag",
            "Hydrate like it's your job", "Water slaps, try it",
        ],
        questions=["Water break?", "Had water yet?", "Bottle empty?", "Sip check?", "Thirsty much?",
                   "One more glass?"],
        actions=["drink a glass of water", "take a big sip", "refill your bottle", "finish that bottle",
                 "have some water", "grab a glass", "chug some water", "sip some water", "fill up your bottle",
                 "drink up", "hydrate now", "take five sips", "drink some water"],
        nouns=["Water", "Hydration", "Your bottle"],
    ),
    "meal": dict(
        keywords=["eat", "meal", "food", "lunch", "dinner", "breakfast", "protein", "fruit", "snack", "calorie",
                  "cook", "nutrition", "salad", "brunch", "veggies", "vegetable", "khana", "nashta", "tiffin"],
        names=["Eat Breakfast", "Lunch", "Dinner", "Healthy Meal", "Protein Intake", "Eat Fruit", "Meal Prep",
               "No Junk Food", "Cook Dinner", "Eat Salad", "Lunch Break", "Healthy Snack", "Breakfast",
               "Eat On Time", "Eat Veggies", "Brunch"],
        emoji=["🥗", "🍲", "🍳"],
        lines=[
            "Your tummy is texting you", "Fuel up, superstar", "Eat like you love yourself",
            "Hungry? That's a sign", "Plate up, champ", "Good food, good mood",
            "Your stomach growled. We heard", "Breakfast is calling, pick up", "Eat the rainbow today",
            "Snack smart, not sad", "Protein is your bestie", "Lunch break is a human right",
            "Feed the machine", "Chew slow, glow more", "Home food hits different",
            "Hangry is not a personality", "Eat now, conquer later", "Your body ordered food",
            "Pause. Plate. Repeat.", "Real food, real energy", "You can't run on empty",
            "Bon appetit, bestie", "Fork it, let's eat", "Mindful bites only",
            "Skipping meals is an L", "This meal is bussin, probably", "Main character eats on time",
            "Veggies are lowkey elite", "Feed yourself, it's self care", "Your plate, your power",
            "Eating well is a whole vibe",
        ],
        questions=["Eaten yet?", "Lunch done?", "Breakfast skipped?", "Hungry?", "Protein today?",
                   "Fruit time?"],
        actions=["eat something healthy", "have your meal", "grab some fruit", "eat your breakfast",
                 "have lunch now", "eat a proper dinner", "add some protein", "eat slowly today",
                 "prep a healthy meal", "fuel your body", "skip the junk", "eat on time", "add some veggies"],
        nouns=["Food", "Lunch", "Your plate"],
    ),
    "fasting": dict(
        keywords=["imd", "if", "intermittent", "fasting", "upvas", "vrat", "roza", "fast", "16:8", "16/8", "18:6", "18/6", "20:4", "omad",
                  "eating window", "diet", "keto", "low carb", "deficit", "calorie deficit", "no sugar diet",
                  "no snacking", "detox diet"],
        names=["IMD", "IF", "Intermittent Fasting", "16:8 Fasting", "18:6 Fast", "OMAD", "Fasting",
               "Eating Window", "Diet", "Diet Plan", "Keto", "Low Carb", "Calorie Deficit", "No Snacking",
               "Fast Until Noon", "IMD Diet", "20:4 Fast"],
        emoji=["🥑", "🍵", "🕐"],
        lines=[
            "Fasting era: unlocked", "Hold the fast, bestie", "Your window is closed, sorry",
            "Eating window opens soon", "Window's open. Eat clean", "Break your fast the smart way",
            "Black coffee is allowed", "Green tea gang, rise", "Hunger is a wave. Surf it",
            "Hours down, gains up", "Your gut is on vacation", "Autophagy is doing its thing",
            "The fast is fast-ing", "No snacking, no cap", "Discipline looks good on you",
            "Stay strong, the clock is ticking", "Almost there, keep the fast",
            "Break the fast, not the plan", "Protein first when you eat", "Water now, food later",
            "The fridge can wait", "Late-night snack? Not today", "Window closed. Kitchen closed.",
            "Your future self is cheering", "Stick to the plan, bestie", "Diet on track, slay",
            "Hunger pangs fade, results stay", "Clean plate, clean fast", "Count hours, not calories",
            "One more hour, you got this", "Fasting hits different today", "Keep it light, keep it right",
        ],
        questions=["Fast going strong?", "Window open yet?", "Water during fast?", "Snack urge?",
                   "Still fasting?", "Ready to break the fast?"],
        actions=["hold your fast", "stay in the fast", "drink water, not snacks", "sip some green tea",
                 "close your eating window", "break your fast gently", "eat a protein-rich meal",
                 "skip the late snack", "stick to your diet", "log your fasting hours", "start your fast now",
                 "keep the kitchen closed", "eat inside your window"],
        nouns=["Fasting", "Your eating window", "The diet"],
    ),
    "workout": dict(
        keywords=["gym", "workout", "exercise", "lift", "weights", "push", "pull", "leg day", "chest", "pushup",
                  "push up", "squat", "plank", "abs", "cardio", "hiit", "strength", "training", "dumbbell",
                  "pullup", "crossfit", "calisthenics"],
        names=["Gym", "Workout", "Exercise", "Push Day", "Leg Day", "Pull Day", "50 Pushups", "Plank", "Abs",
               "Cardio", "HIIT", "Strength Training", "Home Workout", "Squats", "Lift Weights", "Pullups",
               "Chest Day", "Morning Workout", "Calisthenics"],
        emoji=["💪", "🔥", "🥇"],
        lines=[
            "Gains are waiting for you", "Sweat now, shine later", "Your muscles miss you",
            "Leg day is not optional", "Lift heavy, stress light", "The dumbbells are lonely",
            "Just one set. Start.", "Be stronger than your excuses", "Pump it up, legend",
            "Sore today, strong tomorrow", "Flex mode: loading", "Skip the excuse, not the gym",
            "Rep it out!", "Warm up, show up", "Selfie can wait. Lift first.", "Crush it, then brag",
            "Grind now, glow later", "Motivation fades. Habit stays.", "Your couch is not a gym",
            "One more rep, hero", "Beast mode, activate", "Earn that protein shake",
            "Gym arc starts today", "Main character training montage", "Lift like nobody's watching",
            "Gains don't ghost, you do", "No cap, you'll feel amazing", "This workout? Easy W",
            "Your glow up is loading", "Sweat is just glitter, bestie",
        ],
        questions=["Gym time?", "Ready to sweat?", "Workout done?", "One more set?", "Skipping today?",
                   "Leg day?"],
        actions=["hit the gym", "start your workout", "do 20 pushups", "crush one set", "warm up and go",
                 "get your sweat on", "lift something heavy", "do a quick workout", "hold a plank",
                 "train hard today", "show up and lift", "move that body"],
        nouns=["Gym", "Workout", "The barbell"],
    ),
    "walking": dict(
        keywords=["walk", "steps", "stroll", "10k", "10000", "evening walk", "morning walk", "hike", "trek"],
        names=["Morning Walk", "Evening Walk", "10k Steps", "Walk", "Steps Goal", "Post-dinner Walk", "Stroll",
               "Walk 30 Min", "Hike", "Park Walk", "Lunch Walk", "5000 Steps", "Trek", "Brisk Walk",
               "Hot Girl Walk"],
        emoji=["🚶", "👟", "🌳"],
        lines=[
            "Your shoes want an outing", "Step it up, literally", "A walk a day keeps blues away",
            "Fresh air is free", "Walk it off, champ", "Your step count is shy",
            "Move your feet, clear your head", "Small steps, big you", "The park misses you",
            "Outdoor mode: ON", "Leave the phone, take the path", "Every step counts, literally",
            "Take your thoughts for a walk", "Sunlight + steps = happy", "Walk now, scroll later",
            "Go touch some grass", "Ten minutes, big difference", "Walk like you own the street",
            "Steps don't take themselves", "Breathe, walk, repeat", "Hot girl walk, any gender",
            "Main character walk unlocked", "Your playlist needs a walk", "Steps era starts now",
            "Lowkey the best therapy", "Walk it like you talk it", "Your legs want adventure",
            "Window shopping counts too",
        ],
        questions=["Walk time?", "Steps done?", "Quick stroll?", "Shoes on?", "Fresh air break?",
                   "10k today?"],
        actions=["go for a walk", "take a short stroll", "hit your step goal", "walk for ten minutes",
                 "lace up and walk", "take the stairs", "walk around the block", "step outside",
                 "take a quick walk", "stretch your legs", "walk for fifteen minutes", "go around the park"],
        nouns=["Walk", "Your sneakers", "Fresh air"],
    ),
    "running": dict(
        keywords=["run", "running", "jog", "sprint", "5k", "marathon", "km run", "couch to"],
        names=["Morning Run", "Run 5K", "Jog", "Running", "Evening Run", "Sprint Training", "Marathon Prep",
               "Run 3 KM", "Couch to 5K", "Interval Run", "Treadmill Run", "Long Run", "Jogging"],
        emoji=["🏃", "👟", "💨"],
        lines=[
            "Run like the WiFi is ahead", "Your lungs want a workout", "Pace yourself, then race yourself",
            "The road is calling", "Run now, nap later", "Slow run beats no run", "Lace up, legend",
            "One km at a time", "Chase the sunrise", "Outrun your excuses", "Finish line feelings await",
            "Every run counts", "Run for the endorphins", "Your PR is waiting", "Easy pace, big face",
            "Cardio is calling, answer", "Run your own race", "Zoom zoom, bestie", "Keep moving forward",
            "Runner's high is calling", "Short run, big mood", "Morning miles, happy smiles",
            "Run happy, run free", "Sweaty selfie loading", "Run era activated", "Speed is a vibe",
        ],
        questions=["Run today?", "Shoes laced?", "Ready to run?", "Quick 5K?", "Track or road?"],
        actions=["go for a run", "lace up and run", "do a quick jog", "run one easy km", "hit the track",
                 "start your run", "jog for 15 minutes", "chase a new PR", "run at easy pace",
                 "go for a short run", "warm up and jog", "do your intervals"],
        nouns=["Run", "The road", "Your running shoes"],
    ),
    "sleep": dict(
        keywords=["sleep", "bed", "nap", "rest", "bedtime", "lights off", "early to bed", "8 hours"],
        names=["Sleep by 11", "Bedtime", "Sleep Early", "Power Nap", "8 Hours Sleep", "Lights Off",
               "No Late Nights", "Nap", "Wind Down", "Early to Bed", "Rest"],
        emoji=["😴", "🌙", "🛌"],
        lines=[
            "Your pillow misses you", "Sleep is the best skincare", "Lights out, legend", "Dream big, sleep now",
            "Phone down, eyes closed", "Bed is calling, pick up", "Recharge mode: ON",
            "Tomorrow-you needs this", "Netflix will wait. Sleep won't", "Cozy time, no screens",
            "Rest is productive too", "Good night, champion", "Blanket burrito time",
            "Close the tabs, close your eyes", "Sweet dreams loading", "Sleep now, slay tomorrow",
            "The moon says hi", "Snooze responsibly", "Early night, bright morning",
            "Your brain needs a reboot", "Count sheep, not reels", "Shh... bedtime", "Rest like you mean it",
            "Bed > doomscroll", "Sleepy girl era activated", "Eight hours is the move",
            "Log off, bestie. Sleep on", "Your bed is warm and waiting",
        ],
        questions=["Bedtime yet?", "Still up?", "Sleepy?", "Lights off?", "Wind down now?"],
        actions=["go to bed", "leave your phone outside", "switch off the lights", "start winding down",
                 "get some sleep", "take a power nap", "get into bed", "dim the lights", "sleep on time",
                 "close your eyes", "plug in and lie down", "say good night"],
        nouns=["Sleep", "Your pillow", "Bedtime"],
    ),
    "stretching": dict(
        keywords=["stretch", "yoga", "asana", "mobility", "flexib", "surya", "posture", "pilates"],
        names=["Yoga", "Stretch", "Morning Yoga", "Sun Salutation", "Mobility", "Pilates", "Posture Check",
               "Evening Stretch", "Flexibility", "10 Min Yoga", "Back Stretch", "Neck Stretch"],
        emoji=["🧘", "🤸"],
        lines=[
            "Your spine says hello", "Stretch it out, legend", "Bend, don't break", "Unknot your shoulders",
            "Flexibility is a superpower", "Reach for the sky", "Mat time, no excuses",
            "Breathe in, stretch out", "Your back will thank you", "Loosen up, buttercup",
            "Ten minutes of calm", "Posture check, sit tall", "Tight hips? Not today", "Slow flow, big glow",
            "Roll out the mat", "Joints need love too", "Stretch like a cat", "Be bendy, be happy",
            "Stiff neck? Stretch break", "Downward dog, upward mood", "Touch your toes, bestie",
            "Your hamstrings said help", "Pilates princess energy", "Flexible is the new strong",
            "Yoga girlie hours", "Stretch now, thank yourself later",
        ],
        questions=["Mat ready?", "Stretch break?", "Yoga time?", "Shoulders tight?", "Posture okay?"],
        actions=["roll out your mat", "stretch for 5 minutes", "do some yoga", "loosen your shoulders",
                 "fix your posture", "do a forward fold", "stretch your back", "flow for ten minutes",
                 "do a sun salutation", "touch your toes", "do a quick stretch", "hold child's pose",
                 "roll your neck"],
        nouns=["Yoga", "Your mat", "Stretching"],
    ),
    "meds": dict(
        keywords=["med", "medicine", "pill", "tablet", "vitamin", "supplement", "dose", "insulin", "capsule",
                  "multivitamin", "omega", "iron", "b12", "d3", "inhaler", "creatine", "dawai"],
        names=["Take Medicine", "Vitamins", "Vitamin D3", "B12", "Pills", "Supplements", "Omega 3",
               "Iron Tablet", "Multivitamin", "Insulin", "Morning Pill", "Inhaler", "BP Tablet",
               "Thyroid Tablet", "Creatine"],
        emoji=["💊", "⏰"],
        lines=[
            "Pill o'clock, don't forget", "Small pill, big care", "Your health has a reminder",
            "Take it now, not later", "Doctor's orders, bestie", "Vitamins = tiny superheroes",
            "Dose time, legend", "Consistency heals", "Don't leave your meds hanging",
            "Your body is counting on you", "One tablet, then relax", "Health first, always",
            "Swallow, sip, smile", "Med check: pending", "Future you says thanks",
            "Tiny habit, huge payoff", "Stay on track, stay well", "Your vitamins are waiting",
            "Don't skip the small stuff", "Pill first, then chill", "Tiny pill, mighty you",
            "Take care of the machine", "Your pillbox is still full", "Meds on time, all fine",
            "Healthy girl era, take it", "No skipping, no cap", "Self care includes this pill",
            "Vitamin D? Don't skip it",
        ],
        questions=["Meds taken?", "Vitamins done?", "Dose done?", "Pill time?", "Forgot something?"],
        actions=["take your medicine", "take your vitamins", "take your dose", "pop your supplement",
                 "take your tablet", "check your meds", "take it with water", "take today's dose",
                 "take your pills", "have your supplement", "take your capsule"],
        nouns=["Medicine", "Your vitamins", "Your dose"],
    ),
    "skincare": dict(
        keywords=["skin", "skincare", "sunscreen", "spf", "moistur", "serum", "face wash", "facewash", "glow",
                  "cream", "hair", "scalp", "minoxidil", "cleanse", "retinol", "toner"],
        names=["Skincare", "Sunscreen", "Face Wash", "Night Routine", "Moisturize", "Serum", "Hair Oil",
               "Hair Serum", "Scalp Care", "Glow Routine", "SPF", "CTM Routine", "Minoxidil", "Retinol"],
        emoji=["🧴", "✨", "🌸"],
        lines=[
            "Glow up loading", "Your skin deserves this", "SPF is non-negotiable", "Self-care is skincare",
            "Moisturize, don't compromise", "Pamper time, gorgeous", "Clean face, clear mind",
            "Glass skin goals", "Five steps to fabulous", "The mirror is waiting", "Serum time, superstar",
            "Treat your face nicely", "Sun's out, SPF on", "Hair love time", "Your future face says thanks",
            "Glow like you mean it", "Skin first, scroll later", "Soft skin, soft life", "Routine = results",
            "Skin goals start tonight", "Cleanse, tone, glow", "Your face says thank you",
            "Hydrated skin, happy skin", "Glow mode: ON", "Pimples hate routine", "It's giving dewy",
            "That glow? Earned, not filtered", "Skincare is self respect",
        ],
        questions=["Routine done?", "SPF on?", "Moisturized?", "Serum time?", "Face washed?"],
        actions=["do your skincare", "put on sunscreen", "wash your face", "moisturize now", "apply your serum",
                 "oil your hair", "finish your routine", "pamper your skin", "cleanse your face",
                 "apply moisturizer", "do your night routine", "massage your scalp"],
        nouns=["Skincare", "Your skin", "Glow"],
    ),
    "wake": dict(
        keywords=["wake", "wake up", "rise", "alarm", "early", "5am", "6am", "morning routine", "uthna"],
        names=["Wake Up Early", "Wake at 6", "5AM Club", "Morning Routine", "Rise and Shine", "No Snooze",
               "Early Riser", "Wake Up"],
        emoji=["⏰", "🌅", "🐓"],
        lines=[
            "Rise and grind, sunshine", "The sun beat you. Again?", "Snooze button is a liar",
            "The world is waiting, get up", "Good morning, legend", "Early bird gets the peace",
            "New day, new you", "Feet on the floor!", "Open the curtains, champ", "Morning magic starts now",
            "Don't snooze your dreams", "Hello, sunshine", "Stretch, smile, start", "Your day called. Answer it",
            "Win the morning, win the day", "Up and at 'em!", "Coffee is waiting", "The early you is iconic",
            "Morning, sleepyhead", "Alarm rang. You heard it", "Blanket can't hold you forever",
            "Early start, easy day", "Sun's up, so are you", "Get up, glow up", "Five more minutes? Nope",
            "That girl wakes up now", "5AM club energy, bestie",
        ],
        questions=["Awake yet?", "Snoozing again?", "Up already?", "Ready for the day?"],
        actions=["get out of bed", "skip the snooze", "open the curtains", "start your morning",
                 "rise and shine", "splash some water", "wake up now", "get up now", "leave your bed",
                 "put your feet down", "turn off the alarm"],
        nouns=["Morning", "Your alarm", "Sunrise"],
    ),
    "hygiene": dict(
        keywords=["brush", "floss", "teeth", "shower", "bath", "hygiene", "nails", "shave", "groom", "mouthwash"],
        names=["Brush Teeth", "Floss", "Shower", "Night Brush", "Bath", "Cut Nails", "Shave", "Grooming",
               "Mouthwash", "Cold Shower"],
        emoji=["🪥", "🧼", "🦷"],
        lines=[
            "Your teeth want attention", "Floss like nobody's watching", "Fresh breath, fresh start",
            "Brush brush, sparkle sparkle", "Shower thoughts await", "Clean vibes only", "Smile brighter today",
            "Two minutes for a big smile", "Your dentist would be proud", "Fresh is the new cool",
            "Germs, be gone!", "Cold shower, hot energy", "Self-care starts here", "Bright smile loading",
            "Scrub a dub dub", "Feel fresh, feel fab", "Pearly whites, please", "Brush now, sleep happy",
            "Floss is boss", "Clean you, happy you", "Two minutes, then bed", "Fresh mode: ON",
            "Your smile deserves this", "Minty fresh, best breath", "Everything shower? Slay",
            "Clean girl aesthetic, any gender",
        ],
        questions=["Brushed yet?", "Flossed today?", "Shower time?", "Fresh yet?"],
        actions=["brush your teeth", "floss tonight", "take a shower", "use mouthwash", "freshen up",
                 "trim your nails", "take a cold shower", "brush for two minutes", "wash your hands",
                 "take a quick bath"],
        nouns=["Your toothbrush", "Fresh breath", "Shower"],
    ),
    # ---------------------------------------------------------------------------- mind
    "meditation": dict(
        keywords=["meditat", "breath", "pranayam", "mindful", "calm", "zen", "box breath", "breathwork",
                  "dhyan", "anulom"],
        names=["Meditate", "Meditation", "Breathing", "Pranayama", "Mindfulness", "10 Min Calm",
               "Box Breathing", "Morning Meditation", "Breathwork"],
        emoji=["🧘", "🌿", "🍃"],
        lines=[
            "Inhale calm, exhale chaos", "Your mind needs a minute", "Sit. Breathe. Be.", "Peace is a habit",
            "Ten breaths to sanity", "Close your eyes, open your mind", "Quiet mind, loud life",
            "Breathe like you mean it", "Pause the noise", "Calm is a superpower", "Just you and your breath",
            "Zen o'clock", "Let thoughts float by", "Be here now", "A calm you is a cool you",
            "Unplug your brain for 5", "Find your center, champ", "Slow down, you're doing fine",
            "Breathe in the good", "Slow breath, fast calm", "Mind full or mindful?", "Calm down, level up",
            "Five minutes of nothing", "Your inner peace is calling", "Protect your peace, bestie",
            "Overthinking? Breathe instead", "Soft life starts with a breath",
        ],
        questions=["Breathe for a minute?", "Meditation time?", "Feeling scattered?", "Five calm minutes?"],
        actions=["take ten deep breaths", "meditate for 5 minutes", "close your eyes and breathe",
                 "sit in silence", "do box breathing", "find your calm", "be present",
                 "breathe slowly for a minute", "sit and breathe", "try a body scan", "focus on your breath"],
        nouns=["Calm", "Meditation", "Your breath"],
    ),
    "journaling": dict(
        keywords=["journal", "diary", "gratitude", "reflect", "write down", "thankful", "affirmation",
                  "morning pages"],
        names=["Journal", "Gratitude", "Diary", "Night Journal", "3 Good Things", "Reflect", "Morning Pages",
               "Affirmations", "Gratitude List", "Write Thoughts"],
        emoji=["📓", "📝", "💭"],
        lines=[
            "Dear diary, it's me again", "Three good things, go", "Your thoughts deserve paper",
            "Write it out, let it go", "Gratitude changes everything", "Today had a story. Write it",
            "Pen to paper, peace to mind", "Your journal misses your tea", "Reflect, don't regret",
            "What made you smile?", "Unload your brain here", "Small notes, big clarity",
            "Future you will read this", "Count blessings, not likes", "One page, one breath",
            "Spill the tea... on paper", "Your diary is listening", "Write today, read tomorrow",
            "Ink your thoughts", "One line is enough", "Note to self: write", "What did today teach you?",
            "Brain dump time", "Gratitude in three lines", "Your story, your words", "Thank you list, go",
            "Journaling girlie hours", "Manifest it on paper",
        ],
        questions=["Journal tonight?", "Grateful for what?", "Diary time?", "Best part of today?"],
        actions=["write in your journal", "list three good things", "reflect on today", "write one page",
                 "note your wins", "write your affirmations", "jot down your thoughts", "write three lines",
                 "write one gratitude", "fill today's page", "write a brain dump"],
        nouns=["Your journal", "Gratitude", "The diary"],
    ),
    "mood": dict(
        keywords=["mood", "feeling", "check in", "check-in", "emotion", "mental health", "self care",
                  "therapy", "vent"],
        names=["Mood Check", "How Am I Feeling", "Mood Log", "Self Care", "Mental Health Check", "Check In",
               "Emotions", "Therapy Notes", "Feel Good"],
        emoji=["🌈", "💭", "🫶"],
        lines=[
            "How's your heart today?", "It's okay to not be okay", "Check in with you",
            "Feelings are valid, log them", "You matter. Truly.", "Rate your day, be honest",
            "Be kind to yourself today", "Mood check, no judgement", "You're doing better than you think",
            "Name the feeling, tame it", "Sending a virtual hug", "Rainbow after rain", "Your feelings called",
            "Pause and notice", "Proud of you, honestly", "Breathe. You've got this.",
            "How are you, really?", "Rough day? We're here", "Be soft with you",
            "Your feelings deserve a minute", "Bad day? Still proud", "One deep breath for you",
            "Mood log, two seconds", "Heart check, quick one", "You're allowed to rest",
            "Little wins count", "Hug yourself, seriously", "Vibe check, how we doing?",
            "Not you being amazing again",
        ],
        questions=["How are you feeling?", "Mood today?", "Okay, really?", "Need a break?", "Smiling today?"],
        actions=["check in with yourself", "log your mood", "name your feeling", "take a kind pause",
                 "be gentle with yourself", "rate your day", "log how you feel", "take a deep breath",
                 "do something kind for you", "write one feeling", "check your mood"],
        nouns=["Your mood", "Self care", "Your heart"],
    ),
    "nofap": dict(
        keywords=["nofap", "no fap", "n2", "no nut", "nonut", "semen", "retention", "celibacy", "masturbat",
                  "pmo", "urge", "self control", "brahmachar"],
        names=["NoFap", "N2", "No Nut", "Retention", "Self Control", "No PMO", "Urge Control", "Celibacy",
               "Discipline Streak"],
        emoji=["🧠", "🔒", "👑"],
        lines=[
            "Urges pass. Kings stay.", "Discipline is self-respect", "Your streak is your crown",
            "Stay strong, stay you", "Energy saved is energy gained", "Choose the long game",
            "One more day, warrior", "Control is the flex", "You are not your urges", "Redirect that energy",
            "Cold shower > weak moment", "Guard your focus", "Stay locked in, legend", "Mind over impulse",
            "Future you is watching", "Breathe, the wave will pass", "Build the person you respect",
            "Streak > five seconds", "Keep the crown on", "Go outside, reset your mind",
            "Your willpower is growing", "Stay focused, king", "The urge is temporary",
            "Discipline builds kings", "Win this moment", "Your future is worth it", "Protect your energy",
            "Strong mind, strong life", "Locked in era", "Sigma grindset, minus the cringe",
        ],
        questions=["Still strong?", "Urge? Walk it off?", "Streak safe?", "Need a reset walk?"],
        actions=["stay strong today", "protect your streak", "try a cold shower", "go for a walk now",
                 "lock the phone, step out", "redirect your energy", "do 20 pushups instead", "stay busy today",
                 "go to the gym instead", "leave your room", "stay disciplined"],
        nouns=["Discipline", "Your NoFap streak", "Self control"],
    ),
    "noporn": dict(
        keywords=["porn", "no porn", "noporn", "adult content", "nsfw", "explicit"],
        names=["No Porn", "NoPorn", "Quit Porn", "Clean Mind", "No NSFW", "Porn Free", "Digital Purity"],
        emoji=["🚫", "🌱", "🧠"],
        lines=[
            "Clean mind, clear life", "Close the tab, open your life", "Real life > screen life",
            "Your brain is healing", "Every clean day counts", "Guard your eyes, guard your mind",
            "Swap the scroll for a stroll", "You deserve real connection", "Stay clean, stay mean",
            "Rewire, don't retire", "Choose growth today", "The urge lies. You don't.", "Phone down, chin up",
            "Mind detox in progress", "Freedom feels better", "Fill the void with goals",
            "Proud of your clean streak", "Blockers on, focus on", "Your brain deserves better",
            "Stay free, stay you", "Choose real over pixels", "Healing takes time", "Delete, block, move on",
            "You're stronger than the urge", "Clean day, clear head", "Real life is waiting",
            "Healing era, stay in it",
        ],
        questions=["Clean today?", "Clean streak safe?", "Bored? Go outside?", "Phone in hand? Why?"],
        actions=["stay clean today", "close that tab", "keep your phone in another room", "go outside for a bit",
                 "keep your clean streak alive", "turn on your blocker", "call a friend instead",
                 "delete the trigger", "block that site", "stay free today", "splash cold water"],
        nouns=["Your clean streak", "A clear mind", "Freedom"],
    ),
    "quit": dict(
        keywords=["smok", "cigarette", "vape", "alcohol", "drinking", "sugar", "no sugar", "quit", "sober",
                  "nicotine", "tobacco", "caffeine", "junk", "soda", "gutka"],
        names=["No Smoking", "Quit Vaping", "No Sugar", "Sober", "No Alcohol", "Quit Smoking", "No Junk",
               "Less Caffeine", "Nicotine Free", "Sugar Free", "No Soda"],
        emoji=["🚭", "💚", "🌿"],
        lines=[
            "Your lungs say thank you", "One more day without it", "Cravings fade, you stay",
            "Breathe easy, legend", "Sober looks good on you", "Sweet life, less sugar",
            "Every no is a yes to you", "Stronger than the craving", "Money saved, health gained",
            "Craving? Chew gum first", "You quit. You win.", "Clean streak, keep it", "Your heart is healing",
            "Choose you, not the habit", "Freedom tastes better", "Old habit, new you",
            "Proud of every clean day", "Craving lasts 5 minutes", "You're stronger than this",
            "Lungs healing, nice", "Say no, feel proud", "Your body is rebuilding", "Clean lungs, happy you",
            "Habit broken, life open", "Count the money saved", "Smoke-free looks good on you",
            "Sugar crash? Not today", "Fresh air > fresh pack", "Sober and shining", "Kick the habit, champ",
            "Quitting is the flex",
        ],
        questions=["Craving now?", "Still clean?", "Quit streak safe?", "Sugar urge?"],
        actions=["skip it today", "chew gum instead", "wait ten minutes first", "go for a walk, not a smoke",
                 "protect your quit streak", "breathe through the craving", "choose the healthy swap",
                 "say no today", "wait out the craving", "skip the sugar today", "pass on the drink",
                 "skip the smoke break"],
        nouns=["Sobriety", "Your quit streak", "Clean living"],
    ),
    # ----------------------------------------------------------- productivity & learning
    "reading": dict(
        keywords=["read", "book", "novel", "chapter", "page", "kindle", "audiobook", "story", "comic", "manga"],
        names=["Read Novel", "Read 10 Pages", "Reading", "Read a Chapter", "Kindle", "Book Club", "Audiobook",
               "Read Before Bed", "20 Pages", "Read News", "Manga", "Self Help Book"],
        emoji=["📖", "📚", "🔖"],
        lines=[
            "Your book misses you", "One chapter, then dreams", "Plot twist: you read today", "Pages > posts",
            "Open the book, open your mind", "Your bookmark is waiting", "Read like a main character",
            "A few pages a day", "Escape into a story", "Smart is the new hot",
            "The plot thickens... read on", "Readers are leaders", "Your TBR pile is judging",
            "Ten pages, zero excuses", "Lose yourself in a book", "Scroll less, read more",
            "Words over reels", "Chapter time, legend", "Bookworm mode: ON", "Read a page, change a mind",
            "Your story is paused", "Read now, wise later", "Book over phone, tonight", "Turn the page, champ",
            "Booktok would be proud", "Reading era, never ending",
        ],
        questions=["Reading tonight?", "Next chapter?", "Book time?", "10 pages today?"],
        actions=["read ten pages", "finish a chapter", "open your book", "read before bed", "pick up your book",
                 "read for 15 minutes", "continue your story", "move your bookmark", "read one chapter",
                 "read five pages", "open your kindle"],
        nouns=["Your book", "Reading", "The next chapter"],
    ),
    "studying": dict(
        keywords=["study", "studies", "revision", "revise", "exam", "notes", "homework", "assignment", "lecture",
                  "class", "semester", "syllabus", "test prep", "gate", "cat", "upsc", "jee", "neet", "sat",
                  "flashcard", "lab record", "mock", "padhai"],
        names=["Study", "Revision", "Exam Prep", "Homework", "Assignment", "UPSC Prep", "GATE Prep",
               "Flashcards", "Notes", "Semester Prep", "Lecture Review", "Lab Record", "JEE Prep", "Mock Test",
               "SAT Prep"],
        emoji=["📚", "🎓", "📝"],
        lines=[
            "Study time, future topper", "Future topper, open your notes", "Exams don't revise themselves",
            "Small sessions, big marks", "Study now, chill later", "Your degree believes in you",
            "Focus mode, scholar", "One topic at a time", "Knowledge is your flex", "Books open, phone closed",
            "Revise, then relax", "You're smarter than you think", "Pomodoro starts now", "Dream rank loading",
            "Grind today, grin tomorrow", "Notes are waiting, scholar", "Mock test? Bring it on",
            "Brain gains loading", "Syllabus won't finish itself", "Topper vibes only",
            "Study smart, not scared", "Exam season, beast season", "Revision is your weapon",
            "Locked in study arc", "Academic weapon mode: ON", "Study with me, no cap",
        ],
        questions=["Study session?", "Notes ready?", "Revision done?", "One more topic?", "Pomodoro?"],
        actions=["open your notes", "revise one topic", "start a pomodoro", "finish your assignment",
                 "solve a mock test", "review your flashcards", "study for 25 minutes", "make your notes",
                 "revise yesterday's notes", "study one chapter", "solve ten questions"],
        nouns=["Study time", "Your notes", "Revision"],
    ),
    "coding": dict(
        keywords=["code", "coding", "leetcode", "dsa", "program", "dev", "github", "commit", "debug", "project",
                  "algorithm", "algo", "hackerrank", "codeforces", "build", "app", "python", "java", "kotlin",
                  "web"],
        names=["LeetCode", "DSA", "Coding", "Side Project", "GitHub Commit", "Daily Problem", "Codeforces",
               "Learn Python", "Build App", "Debug", "Kotlin Practice", "Web Dev", "100 Days of Code"],
        emoji=["💻", "🐛", "🚀"],
        lines=[
            "Solve one problem!", "Your IDE misses you", "Commit something today", "Bugs fear you, legend",
            "One problem a day", "Ship it, don't skip it", "Green squares look good", "Debug mode: ON",
            "Hello world, hello habit", "Your streak needs a commit", "Code now, deploy dreams",
            "Arrays won't sort themselves", "Ctrl+S your progress", "Coffee + code = magic",
            "Build it, break it, fix it", "Logic > luck", "Merge your goals today", "Push code, not excuses",
            "Recursion: do it again tomorrow", "Rubber duck is waiting", "Code, coffee, conquer",
            "Your keyboard misses you", "One commit keeps the streak", "Compile your dreams",
            "Git push your limits", "Let him cook (the code)", "It works on my machine, ship it",
        ],
        questions=["Code today?", "One problem?", "Commit done?", "Bug hunting?", "LeetCode time?"],
        actions=["solve one problem", "push a commit", "open your IDE", "fix one bug", "code for 30 minutes",
                 "finish one feature", "practice one algorithm", "write some code", "solve a LeetCode problem",
                 "write one function", "refactor one file"],
        nouns=["Code", "Your repo", "LeetCode"],
    ),
    "focus": dict(
        keywords=["focus", "deep work", "pomodoro", "work", "office", "task", "todo", "to do", "plan", "planning",
                  "productiv", "email", "inbox", "meeting", "schedule", "agenda"],
        names=["Deep Work", "Focus Session", "Plan the Day", "To-Do List", "Inbox Zero", "Pomodoro",
               "Work Block", "Top 3 Tasks", "Weekly Plan", "Clear Emails", "Office Work", "No Distractions"],
        emoji=["🎯", "⏳", "🔕"],
        lines=[
            "Do the hard thing first", "Notifications off, genius on", "One task. Full focus.",
            "Deep work, deep wins", "Eat the frog today", "Distractions, be gone", "Plan it, then slay it",
            "Busy is not productive", "Focus is your superpower", "Single-tasking is the new cool",
            "Inbox zero, hero", "Tick tick, task done", "Big goals, tiny steps", "25 minutes. Go.",
            "Make today count", "Your to-do list misses you", "Less scroll, more goal",
            "Focus now, freedom later", "One thing at a time, boss", "Distraction-free zone",
            "Hustle smart today", "Productive you is iconic", "Get it done, then have fun",
            "Your deadline says hi", "Time-block it, rock it", "Locked in, no notifications",
            "CEO of getting things done",
        ],
        questions=["Focus time?", "Top task done?", "Planned today?", "Phone silent?", "One pomodoro?"],
        actions=["start a focus block", "silence your phone", "plan your day", "do your top task",
                 "clear your inbox", "work for 25 minutes", "write your to-do list", "close extra tabs",
                 "finish one task", "block your calendar", "focus for 25 minutes"],
        nouns=["Focus", "Deep work", "Your to-do list"],
    ),
    "practice": dict(
        keywords=["practice", "guitar", "piano", "sing", "music", "language", "duolingo", "spanish", "french",
                  "german", "japanese", "korean", "english", "vocab", "speaking", "instrument", "violin", "drums",
                  "flute", "chess", "typing", "dance", "ukulele", "riyaz"],
        names=["Guitar Practice", "Piano", "Duolingo", "Learn Spanish", "Japanese", "Vocab", "Singing",
               "Violin", "Drums", "Chess Puzzle", "Typing Practice", "Dance Practice", "Speak English",
               "French", "Learn Korean", "Ukulele"],
        emoji=["🎵", "🎸", "🌍"],
        lines=[
            "Practice makes progress", "Your guitar is gathering dust", "The owl is watching",
            "Ten minutes of practice", "Scales today, stages tomorrow", "Say it in a new language",
            "Your streak is singing", "Every pro was a beginner", "Hola! Practice time",
            "Little daily, big fluency", "Play it again, champ", "Muscle memory loading", "Learn one new word",
            "Strum, sing, smile", "Practice now, perform later", "Keys are calling", "Fingers ready, champ",
            "Fluency is a daily habit", "Your teacher would be proud", "Ten minutes, new skill",
            "Hit the right notes today", "Your owl is not happy", "Learning era, stay in it",
            "Talent is just reps, bestie", "Rockstar arc loading",
        ],
        questions=["Practice today?", "New word today?", "Lesson time?", "Ten minutes?", "Scales done?"],
        actions=["practice for 15 minutes", "do your lesson", "play your scales", "learn five new words",
                 "pick up your instrument", "keep your Duolingo streak", "speak out loud",
                 "practice your scales", "finish one lesson", "learn one new phrase"],
        nouns=["Practice", "Your lesson", "Your instrument"],
    ),
    # ----------------------------------------------------------------------- life & home
    "chores": dict(
        keywords=["clean", "laundry", "dishes", "tidy", "chore", "declutter", "sweep", "mop", "room",
                  "make bed", "kitchen", "grocer", "trash", "iron clothes", "organize", "vacuum", "safai"],
        names=["Clean Room", "Laundry", "Dishes", "Make Bed", "Declutter", "Groceries", "Take Out Trash",
               "Kitchen Clean", "Organize Desk", "Iron Clothes", "Vacuum", "Reset Sunday"],
        emoji=["🧹", "🧺", "🧽"],
        lines=[
            "Your room called. It's messy", "Tidy space, tidy mind", "Dishes won't wash themselves",
            "Laundry mountain alert", "Ten minutes of tidying", "Make your bed, make your day",
            "Clean as you go, pro", "Declutter like a boss", "A clean desk is a calm desk",
            "Clutter out, peace in", "Chore now, chill later", "Sparkle mode: ON",
            "Future you loves a clean home", "Spin cycle, win cycle", "Mop it like it's hot",
            "Fold it, don't hold it", "Clean space, clear mind", "Laundry day, slay day",
            "Sink full? Not for long", "Tidy up, chill out", "Your home deserves love", "Five minute tidy, go",
            "Clean home, happy you", "Bed made, day made", "Reset era, clean it up",
            "Clean room, clean aura",
        ],
        questions=["Room tidy?", "Laundry done?", "Dishes waiting?", "Bed made?", "Trash out?"],
        actions=["tidy up for 10 minutes", "do the dishes", "start the laundry", "make your bed",
                 "take out the trash", "clean your desk", "fold your clothes", "sweep the floor",
                 "clean the kitchen", "put things back", "load the washing machine", "wipe the table"],
        nouns=["Your room", "Laundry", "A clean home"],
    ),
    "finance": dict(
        keywords=["budget", "money", "saving", "save", "expense", "spend", "finance", "invest", "sip", "bill",
                  "track spending", "accounts", "emi", "rent", "stock", "upi", "crypto"],
        names=["Track Expenses", "Budget", "Save Money", "Invest", "SIP", "Pay Bills", "No Spend Day",
               "Log Expenses", "Check Bank", "Rent", "EMI", "Savings Goal"],
        emoji=["💰", "📈", "💸"],
        lines=[
            "Track it before it vanishes", "Your wallet wants a word", "Budget now, ballin' later",
            "Small savings, big dreams", "Know where it goes", "Rich habits start today",
            "No-spend day, you got this", "Future you is rich. Help them", "Compound interest loves you",
            "Log today's spends", "Money mindful mode", "Bills paid, stress fade", "Every penny counts",
            "Invest in you, literally", "Cart full? Think twice", "Spend smart, live large",
            "Your savings say hi", "Money talks, track it", "Budget is a boss move",
            "Wallet check, quick one", "Know your numbers, champ", "Save first, spend later",
            "Investment o'clock", "Bills due? Pay now", "Rich auntie energy", "Financially literate era",
            "Don't let the cart win",
        ],
        questions=["Expenses logged?", "Budget check?", "Bills paid?", "Saved today?", "Impulse buy?"],
        actions=["log your expenses", "check your budget", "pay your bills", "move money to savings",
                 "skip one impulse buy", "review your spending", "check your SIP", "note today's spending",
                 "update your budget", "save a little today", "check your accounts"],
        nouns=["Your budget", "Savings", "Your wallet"],
    ),
    "social": dict(
        keywords=["call", "family", "friend", "mom", "dad", "mum", "parents", "text", "connect", "social",
                  "network", "grandma", "grandpa", "message", "maa", "papa", "nani", "dadi", "girlfriend", "boyfriend", "wife", "husband",
                  "date night"],
        names=["Call Mom", "Call Family", "Text a Friend", "Call Dad", "Call Parents", "Call Grandma",
               "Catch Up", "Network", "Reply Messages", "Date Night", "Call Grandparents", "Meet Friends"],
        emoji=["📞", "🤝", "💬"],
        lines=[
            "Mom would love a call", "Your people miss you", "One call can make a day", "Text back, legend",
            "Friendship needs watering", "Say hi, it's free", "Family first, always",
            "Catch up, don't hang up", "A voice beats a text", "Someone is thinking of you",
            "Love them loudly", "Pick up the phone, champ", "Make someone smile today",
            "Five minutes of love", "Send that message", "Good vibes, good tribe",
            "Call someone you love", "Ring ring, it's family", "Your best friend misses you",
            "Be the friend who calls", "Love is a phone call away", "Reply. They're waiting",
            "Catch up over coffee", "Your squad needs you", "Voice notes count too",
            "Check on your strong friend", "Don't leave them on read", "Bestie check-in time",
        ],
        questions=["Called home?", "Text back?", "Miss someone?", "Catch up today?"],
        actions=["call your family", "text a friend", "call your mom", "reply to messages",
                 "check on a friend", "plan a catch up", "send a voice note", "call your dad",
                 "call someone you love", "message a friend", "check on your people"],
        nouns=["Family", "Your friends", "A phone call"],
    ),
    "creative": dict(
        keywords=["draw", "sketch", "paint", "art", "write", "writing", "blog", "poem", "design", "photo",
                  "video", "edit", "content", "craft", "hobby", "create", "doodle", "story writing", "youtube",
                  "podcast"],
        names=["Draw", "Sketch", "Write Blog", "Painting", "Poetry", "Photography", "Edit Video",
               "Content Creation", "Doodle", "Craft", "Write Story", "Design Practice", "YouTube Video",
               "Podcast"],
        emoji=["🎨", "💡", "🎬"],
        lines=[
            "Create something, anything", "Your canvas is waiting", "Make art, not excuses",
            "Ideas need a home", "Doodle your heart out", "Write the first line", "Creativity is a muscle",
            "Make something messy", "The muse is calling", "Ten minutes of magic", "Blank page? Fill it",
            "Art is therapy", "Your story deserves telling", "Inspiration loves action",
            "Create, don't compare", "Shoot, edit, post", "Sketch it out, legend", "Make something today",
            "Ideas don't wait", "Art time, artist", "Your sketchbook is lonely", "Create first, edit later",
            "Paint your mood", "One idea, one page", "Your project misses you", "Creator era, go post",
            "Romanticize your art time",
        ],
        questions=["Create today?", "Sketch time?", "First line written?", "Idea brewing?"],
        actions=["sketch for 10 minutes", "write one paragraph", "make something new", "edit your video",
                 "pick up your brush", "write a short poem", "shoot one photo", "work on your project",
                 "draw something small", "write for ten minutes", "brainstorm one idea"],
        nouns=["Your canvas", "Creativity", "Your sketchbook"],
    ),
    "pets": dict(
        keywords=["dog", "cat", "pet", "puppy", "kitten", "feed", "litter", "vet", "fish", "bird",
                  "walk the dog"],
        names=["Feed Dog", "Walk Dog", "Feed Cat", "Litter Box", "Pet Care", "Feed Fish", "Vet Visit",
               "Groom Pet", "Play with Dog", "Feed Bird"],
        emoji=["🐶", "🐱", "🐾"],
        lines=[
            "Someone furry is hungry", "Paws up, food time", "Your pet is staring at you", "Walkies? Walkies!",
            "Best friend needs you", "Treat time, hooman", "Tail wags incoming", "Purrfect time to feed",
            "Belly rubs are overdue", "Your floof misses you", "Fill the bowl, win the love", "Woof means now",
            "Meow means dinner", "Happy pet, happy home", "Playtime, pawsome friend", "Your pet is waiting",
            "Food bowl empty? Uh oh", "Furry friend alert", "Who's a good boy? Feed him",
            "Kitty wants dinner", "Puppy eyes activated", "Bark bark, food time",
            "Your pet's tummy rumbled", "Snack time for the floof", "Walk the woof", "Love them, feed them",
            "Fishy wants flakes", "Your pet counts on you", "Pet care is self care",
            "Zoomies incoming, take him out", "Litter duty, hero", "Fresh water for the furball",
            "Pet hugs, best hugs", "The floof has demands", "Certified pet parent moment",
        ],
        questions=["Pet fed?", "Walkies time?", "Bowl full?", "Litter clean?"],
        actions=["feed your pet", "take the dog out", "clean the litter box", "fill the water bowl",
                 "play with your pet", "give some cuddles", "feed your dog", "feed your cat", "walk your dog",
                 "refill the food bowl", "brush your pet", "give a treat"],
        nouns=["Your pet", "Your furry friend", "Food bowl"],
    ),
    "plants": dict(
        keywords=["plant", "garden", "water plants", "seed", "succulent", "balcony", "flower", "repot", "tulsi"],
        names=["Water Plants", "Gardening", "Balcony Garden", "Repot Plant", "Plant Care", "Flowers",
               "Succulents", "Herb Garden", "Tulsi"],
        emoji=["🌱", "🪴", "💦"],
        lines=[
            "Your plants are thirsty", "Leaf it to you, champ", "Grow with your garden",
            "Green friends need love", "Water the babies", "Photosynthesis needs help", "Plant parent duty",
            "Happy leaves, happy you", "A little water, a lot of life", "Your garden misses you",
            "Bloom where you're planted", "Rooting for you, literally", "Soil check, gardener",
            "Thirsty leaves alert", "Water the green gang", "Plants can't text, so we did",
            "Green thumb time", "Soil dry? Fix it", "Grow, baby, grow", "Plant mom duty", "Plant dad duty",
            "Leafy friends need you", "Sun and water, that's all", "Dry soil, sad plant",
            "Keep the green alive", "Watering can, assemble!", "Your balcony needs love",
            "Blooms need water", "Plant parent era", "Your monstera is judging",
        ],
        questions=["Plants watered?", "Soil dry?", "Garden time?", "Leaves happy?"],
        actions=["water your plants", "check the soil", "trim dead leaves", "give them sunlight",
                 "mist your plants", "repot one plant", "water the garden", "check your plants",
                 "give them water", "turn your pots", "feed your plants"],
        nouns=["Your plants", "The garden", "Green babies"],
    ),
    "screen_break": dict(
        keywords=["screen", "detox", "phone", "social media", "instagram", "reels", "tiktok", "shorts",
                  "offline", "unplug", "eye break", "20-20-20", "digital", "no phone", "doomscroll"],
        names=["Screen Break", "Digital Detox", "No Phone", "Less Reels", "Eye Break", "Offline Hour",
               "No Social Media", "20-20-20", "Unplug", "Phone Free Dinner", "No Doomscrolling", "Less TikTok"],
        emoji=["📵", "👀", "🔌"],
        lines=[
            "Your eyes need a vacation", "Reels can wait, life can't", "Unplug to recharge",
            "Look up, the sky is free", "Doomscroll? Bloomscroll instead", "20 seconds, look far away",
            "Phone down, world up", "Touch grass, not glass", "Your thumb needs a break",
            "Be offline, be fine", "Real life has better graphics", "Blink, stretch, breathe",
            "Instagram will survive", "Log off, live on", "Phone break, brain break", "Look away, legend",
            "Your eyes say ouch", "Scroll less, live more", "Put it down, look around", "Eyes need rest too",
            "Unplug for ten", "Reels are a trap", "Phone face down, please", "Digital detox, go",
            "Your screen time is crying", "Chronically online? Log off", "The algorithm can wait",
            "Brain rot? Not today",
        ],
        questions=["Still scrolling?", "Eyes tired?", "Phone break?", "Offline for 10?"],
        actions=["put your phone away", "look far for 20 seconds", "take a screen break",
                 "go offline for a bit", "close the reels", "rest your eyes", "switch off notifications",
                 "look out the window", "keep your phone aside", "blink and look away",
                 "lock your phone for a bit"],
        nouns=["Screen time", "Your phone", "Your eyes"],
    ),
    "prayer": dict(
        keywords=["pray", "prayer", "pooja", "puja", "namaz", "salah", "chant", "jaap", "aarti", "temple",
                  "church", "gurbani", "bible", "quran", "gita", "spiritual", "mantra", "worship"],
        names=["Pooja", "Namaz", "Prayer", "Morning Prayer", "Chanting", "Read Gita", "Temple Visit",
               "Gurbani", "Bible Reading", "Mantra", "Worship"],
        emoji=["🙏", "🪔", "🕊"],
        lines=[
            "A moment of gratitude", "Peace begins within", "Faith over fear", "Light a lamp, light your day",
            "Pause and pray", "Blessings are counting on you", "Soul time, not screen time",
            "Calm heart, kind mind", "Start with gratitude", "Your quiet time is here",
            "Spiritual recharge, now", "Fold your hands, free your mind", "Grateful heart, happy life",
            "Pray, then play", "Gratitude o'clock", "Your soul says hi", "Faith time, five minutes",
            "Peace is a prayer away", "Hands folded, heart open", "Thank the universe today",
            "Morning prayer, good day", "Quiet time with God", "Pray more, worry less",
            "Spirit check, quick one", "Blessed and grateful", "Chant, breathe, smile",
            "Prayer time, don't miss it", "Blessed era, stay humble",
        ],
        questions=["Prayer time?", "Pooja done?", "A quiet minute?", "Grateful today?"],
        actions=["take a moment to pray", "light the lamp", "say your prayers", "read a few verses",
                 "chant for 5 minutes", "give thanks", "say a short prayer", "do your pooja",
                 "light a candle", "read one verse", "sit in prayer", "chant your mantra"],
        nouns=["Prayer", "Your quiet time", "Faith"],
    ),
    # --------------------------------------------------------------------------- fallback
    "other": dict(
        keywords=[],
        names=["Daily Goal", "Habit", "My Task", "Routine", "Personal Goal", "New Habit", "Challenge",
               "Check List", "Goal", "Reminder", "Task A", "Practice Habit", "Do The Thing"],
        emoji=["✅", "⭐", "🙌"],
        lines=[
            "Small habit, big you", "Your streak is waiting", "Do it now, thank us later",
            "Tick it, then chill", "Consistency is your superpower", "One step at a time",
            "You said you would. Go!", "Future you is cheering", "Make today a tick day",
            "Habits build legends", "Just start. That's it.", "Show up for yourself", "Discipline > motivation",
            "Win the day, one tick", "Progress over perfection", "Little by little, a lot",
            "Don't break the chain", "You're on a roll", "Keep the promise to you", "Check it off, champ",
            "Yesterday you would be proud", "Tick it off, superstar", "Your goal is waiting",
            "Do it for future you", "Streaks love consistency", "One more tick, legend",
            "Easy task, big win", "Don't let it slide", "Do the thing!", "Main character habit unlocked",
            "Get that W today", "No cap, you can do this",
        ],
        questions=["Done yet?", "Ready to tick?", "Chain still unbroken?", "Quick win?", "Still on it?"],
        actions=["do it now", "tick this off", "keep your streak", "start for 5 minutes", "make progress today",
                 "show up today", "finish your task", "finish it today", "get it done", "complete your goal",
                 "do it right now"],
        nouns=["Your habit", "Your streak", "Today's goal"],
    ),
}

# Generic pieces (English + a little Gen Z)
OPENERS = ["Psst,", "Hey,", "Quick one:", "Reminder:", "Hey bestie,", "Friendly nudge:", "Real talk:",
           "No cap,", "Lowkey,", "Ahem,", "Future you says:", "Plot twist:", "Not to nag, but",
           "Gentle reminder:", "Yo,", "Okay legend,", "Small win:", "Main character move:", "Breaking news:",
           "Hello hello,", "Vibe check:", "Your sign to", "POV: you"]

CLOSERS = [", bestie", ", legend", " now", " today", ", please?", ", promise?", ", no excuses", " - you got this",
           ", just 5 min", " rn", ", no cap", ", superstar", " and slay", " fr"]

# Templates for plain nouns ("Water", "Gym") and for possessive ones ("Your bottle").
NOUN_TEMPLATES = ["{N} o'clock!", "{N} > excuses", "{N} first, scroll later", "{N} time? Yes, now.",
                  "Not a drill: {n} time", "You + {n} = iconic", "{N} is calling", "{N}, then chill",
                  "Okay but {n}?", "{N} era starts now", "It's giving {n}", "POV: {n} time"]
POSSESSIVE_TEMPLATES = ["{N} is calling", "{N} misses you", "Okay but {n}?", "Don't ghost {n}",
                        "{N} is waiting", "{N} needs you now", "Don't leave {n} on read"]
